/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.gerais;

import Control.ComandosBanco;
import Control.ComandosGerais;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Borim
 */
public class ConfigPessoal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TesteFrame
     */
       
    private String branco = null;
    private boolean alternativa = true;
    ComandosBanco comandobanco = new ComandosBanco();
    private boolean alternativa2 = true;
    
    public ConfigPessoal() {
        initComponents();
        setVisible(true);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarusuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        concluiralteracao = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        senha1 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        usuario1 = new javax.swing.JTextField();
        nomeusuario = new javax.swing.JTextField();
        datadehoje1 = new javax.swing.JTextField();
        cpf1 = new javax.swing.JTextField();
        responsavel1 = new javax.swing.JTextField();
        usuariocriacao1 = new javax.swing.JTextField();
        tipo2 = new javax.swing.JTextField();
        ultimaalteracao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Meus Dados");

        alterarusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel3.setText("Usuário");

        jLabel9.setText("Tipo");

        jLabel11.setText("Nome");

        jLabel14.setText("Usuário");

        jLabel15.setText("Responsável");

        jLabel16.setText("E-mail");

        concluiralteracao.setBackground(new java.awt.Color(0, 255, 0));
        concluiralteracao.setText("Concluir");
        concluiralteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluiralteracaoalteracaoActionPerformed(evt);
            }
        });

        alterar.setBackground(new java.awt.Color(255, 255, 51));
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alterar)
                .addGap(18, 18, 18)
                .addComponent(concluiralteracao)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluiralteracao)
                    .addComponent(alterar)))
        );

        jLabel17.setText("Data Criação");

        jLabel18.setText("CPF");

        jLabel19.setText("Senha");

        senha1.setEditable(false);
        nomeusuario.setText(x);

        jLabel20.setText("Usuario Criação");

        nome1.setEditable(false);
        nomeusuario.setText(x);

        email1.setEditable(false);

        usuario1.setEditable(false);

        nomeusuario.setEditable(false);

        datadehoje1.setEditable(false);

        cpf1.setEditable(false);

        responsavel1.setEditable(false);

        usuariocriacao1.setEditable(false);

        tipo2.setEditable(false);

        ultimaalteracao.setEditable(false);

        jLabel22.setText("Última Alter.");

        javax.swing.GroupLayout alterarusuarioLayout = new javax.swing.GroupLayout(alterarusuario);
        alterarusuario.setLayout(alterarusuarioLayout);
        alterarusuarioLayout.setHorizontalGroup(
            alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarusuarioLayout.createSequentialGroup()
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, alterarusuarioLayout.createSequentialGroup()
                        .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, alterarusuarioLayout.createSequentialGroup()
                        .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, alterarusuarioLayout.createSequentialGroup()
                                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(cpf1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(responsavel1)
                                    .addComponent(datadehoje1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(28, 28, 28)
                                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(alterarusuarioLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(alterarusuarioLayout.createSequentialGroup()
                                        .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ultimaalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(usuariocriacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(alterarusuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        alterarusuarioLayout.setVerticalGroup(
            alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarusuarioLayout.createSequentialGroup()
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarusuarioLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGroup(alterarusuarioLayout.createSequentialGroup()
                        .addComponent(cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(usuariocriacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datadehoje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(ultimaalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        senha1.setText(comandobanco.buscaDados(nomeusuario.getText(), "senha"));
        nome1.setText(comandobanco.buscaDados(nomeusuario.getText(), "nome"));
        nomeusuario.setText(x);

        email1.setText(comandobanco.buscaDados(nomeusuario.getText(), "email"));
        usuario1.setText(x);
        nomeusuario.setText(x);
        datadehoje1.setText(comandobanco.buscaDados(usuario1.getText(), "datacriacao"));
        cpf1.setText(comandobanco.buscaDados(usuario1.getText(), "cpf"));
        responsavel1.setText(comandobanco.buscaDados(usuario1.getText(), "responsavel"));
        usuariocriacao1.setText(comandobanco.buscaDados(usuario1.getText(), "usuariocriacao"));
        if(comandobanco.buscaDados(nomeusuario.getText(), "tipo").equals("0")){
            tipo2.setText("Consultor");
        }else if(comandobanco.buscaDados(nomeusuario.getText(), "tipo").equals("1")){
            tipo2.setText("Gerente");
        } else{
            tipo2.setText("Apoio");
        }
        //ultimaalteracao.setText(x);

        ultimaalteracao.setText(comandobanco.buscaDados(nomeusuario.getText(), "ultimaalteracao"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(alterarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alterarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Conclui alteração no usuário
    private void concluiralteracaoalteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluiralteracaoalteracaoActionPerformed
        // TODO add your handling code here:

        
        comandobanco.atualizaDadosCadastro(usuario1.getText(), "email", email1.getText());

        comandobanco.atualizaDadosCadastro(usuario1.getText(), "senha", senha1.getText());
        


        email1.setEditable(false);

        senha1.setEditable(false);
        
       JOptionPane.showMessageDialog(rootPane, "Alterações realizadas com sucesso");
           
           
           
     
          
    }//GEN-LAST:event_concluiralteracaoalteracaoActionPerformed
    
    
    //Habilita edição
    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
            
        if(alternativa){ //Habilita edição dos botões
           email1.setEditable(true);
           senha1.setEditable(true); 
        } else{ //Desabilita edição dos botões
           email1.setEditable(false);
           senha1.setEditable(false);
           
        }
        
        alternativa = !alternativa;   //inverte bolleano para efetuar opções alternadas 
        
    }//GEN-LAST:event_alterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JPanel alterarusuario;
    private javax.swing.JButton concluiralteracao;
    private javax.swing.JTextField cpf1;
    private javax.swing.JTextField datadehoje1;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nome1;
    private javax.swing.JTextField nomeusuario;
    private javax.swing.JTextField responsavel1;
    private javax.swing.JPasswordField senha1;
    private javax.swing.JTextField tipo2;
    private javax.swing.JTextField ultimaalteracao;
    private javax.swing.JTextField usuario1;
    private javax.swing.JTextField usuariocriacao1;
    // End of variables declaration//GEN-END:variables

 public void setPosicao() { //Algoritmo para centralizar Jinternalframe
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }


 //Pega o nome do usuário logado
String x = ComandosGerais.getHistorico();


}

