/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Telas.gerais.AddCliente;
import Telas.gerais.CarteiraPedidos;
import Telas.gerais.ConsultaCliente;
import Telas.gerais.EstatistcaCliente;
import Telas.gerais.HistoricoCompras;
import Telas.gerais.ImplantarPedido;
import Telas.gerais.AddItem;
import Telas.gerais.EspalharMensagem;
import Telas.gerais.RelatorioEstoque;
import Telas.gerais.EstatisticaConsultor;


/**
 *
 * @author Lucas Borim
 */
public class TelaGerente extends javax.swing.JFrame {
    
    
      ImplantarPedido implantarpedido; //janela implantar
      AddCliente adicionarcliente; //janela consulta cadastro
      ConsultaCliente consultacliente; //janela consulta cliente
      EstatistcaCliente estatisticacliente; //janela estatistica de cliente
      HistoricoCompras historicocompras; //janela Historico de compras
      CarteiraPedidos carteirapedidos; //janela carteira de pedidos
      AddItem relatorioclientes; //janela Relatorio de clientes
      RelatorioEstoque relatorioestoque; //janela relatorio de estoque
      AddItem additem; //Janela para adicionar item
      EstatisticaConsultor estatisticaconsultor; //Janela para estatistica equipe
      EspalharMensagem espalharmensagem; //Janela com chat para espalhar mensagem
    

    /**
     * Cria Classe principal
     */
    public TelaGerente() { //Método construtor
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH); //Inicia Maximizado
        setLocationRelativeTo(null); //Centraliza a tela
        setTitle("Gerente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btnimplantar = new javax.swing.JButton();
        btnaddcliente = new javax.swing.JButton();
        btncarteirapedido = new javax.swing.JButton();
        btnconsultacadastro = new javax.swing.JButton();
        btnestatistica = new javax.swing.JButton();
        btnhistorico = new javax.swing.JButton();
        btnrelatoriodeestoque = new javax.swing.JButton();
        btnadditem = new javax.swing.JButton();
        btnestatisticaequipe = new javax.swing.JButton();
        btnespalharmensagem = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(isAlwaysOnTopSupported());
        setBackground(java.awt.SystemColor.textHighlight);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 2));

        jToolBar2.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setBorderPainted(false);
        jToolBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnimplantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/addpedidos.png"))); // NOI18N
        btnimplantar.setFocusable(false);
        btnimplantar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnimplantar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnimplantar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnimplantarMouseClicked(evt);
            }
        });
        jToolBar2.add(btnimplantar);

        btnaddcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/addcliente.png"))); // NOI18N
        btnaddcliente.setFocusable(false);
        btnaddcliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaddcliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnaddcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddclienteMouseClicked(evt);
            }
        });
        jToolBar2.add(btnaddcliente);

        btncarteirapedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/carteira pedido.png"))); // NOI18N
        btncarteirapedido.setFocusable(false);
        btncarteirapedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncarteirapedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncarteirapedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncarteirapedidoMouseClicked(evt);
            }
        });
        jToolBar2.add(btncarteirapedido);

        btnconsultacadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/consultacadastro.png"))); // NOI18N
        btnconsultacadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconsultacadastro.setFocusable(false);
        btnconsultacadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnconsultacadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnconsultacadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconsultacadastroMouseClicked(evt);
            }
        });
        jToolBar2.add(btnconsultacadastro);

        btnestatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/estatisticacliente.png"))); // NOI18N
        btnestatistica.setFocusable(false);
        btnestatistica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnestatistica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnestatistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnestatisticaMouseClicked(evt);
            }
        });
        jToolBar2.add(btnestatistica);

        btnhistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/historicocompras.png"))); // NOI18N
        btnhistorico.setFocusable(false);
        btnhistorico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhistorico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhistoricoMouseClicked(evt);
            }
        });
        jToolBar2.add(btnhistorico);

        btnrelatoriodeestoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/relatorioestoque.png"))); // NOI18N
        btnrelatoriodeestoque.setFocusable(false);
        btnrelatoriodeestoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrelatoriodeestoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrelatoriodeestoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrelatoriodeestoqueMouseClicked(evt);
            }
        });
        jToolBar2.add(btnrelatoriodeestoque);

        btnadditem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Principal2/additem.png"))); // NOI18N
        btnadditem.setFocusable(false);
        btnadditem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnadditem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnadditem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadditemMouseClicked(evt);
            }
        });
        jToolBar2.add(btnadditem);

        btnestatisticaequipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Gerente/Estatisticaequipe.png"))); // NOI18N
        btnestatisticaequipe.setFocusable(false);
        btnestatisticaequipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnestatisticaequipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnestatisticaequipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnestatisticaequipeMouseClicked(evt);
            }
        });
        jToolBar2.add(btnestatisticaequipe);

        btnespalharmensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Menu Gerente/Espalharmsg.png"))); // NOI18N
        btnespalharmensagem.setFocusable(false);
        btnespalharmensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnespalharmensagem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnespalharmensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnespalharmensagemMouseClicked(evt);
            }
        });
        jToolBar2.add(btnespalharmensagem);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(690, 490));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opções");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimplantarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnimplantarMouseClicked
        
        //Abrir novo JInternalFrame
        implantarpedido = new ImplantarPedido();
        implantarpedido.setVisible(true);
        jDesktopPane1.add(implantarpedido);
        implantarpedido.setPosicao();
        implantarpedido.toFront();
    }//GEN-LAST:event_btnimplantarMouseClicked

    private void btnaddclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddclienteMouseClicked
        
        //Abrir novo JInternalFrame
        adicionarcliente = new AddCliente();
        adicionarcliente.setVisible(true);
        jDesktopPane1.add(adicionarcliente);
        adicionarcliente.setPosicao();
        adicionarcliente.toFront();
    }//GEN-LAST:event_btnaddclienteMouseClicked

    private void btncarteirapedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncarteirapedidoMouseClicked
        //Alrotimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(carteirapedidos == null){
            carteirapedidos = new CarteiraPedidos();
            carteirapedidos.setVisible(true);
            jDesktopPane1.add(carteirapedidos);
            carteirapedidos.setPosicao();
            carteirapedidos.toFront();
        }
        else if(!carteirapedidos.isVisible()){
            carteirapedidos.setVisible(true);
            jDesktopPane1.add(carteirapedidos);
            carteirapedidos.setPosicao();
            carteirapedidos.toFront();
        }
    }//GEN-LAST:event_btncarteirapedidoMouseClicked

    private void btnconsultacadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultacadastroMouseClicked
        // TODO add your handling code here:
        if(consultacliente == null){
            consultacliente = new ConsultaCliente();
            consultacliente.setVisible(true);
            jDesktopPane1.add(consultacliente);
            consultacliente.setPosicao();
            consultacliente.toFront();
        }
        else if(!consultacliente.isVisible()){
            consultacliente.setVisible(true);
            jDesktopPane1.add(consultacliente);
            consultacliente.setPosicao();
            consultacliente.toFront();
        }
    }//GEN-LAST:event_btnconsultacadastroMouseClicked

    private void btnestatisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnestatisticaMouseClicked
        // TODO add your handling code here:
        //Algoritimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(estatisticacliente == null){
            estatisticacliente = new EstatistcaCliente();
            estatisticacliente.setVisible(true);
            jDesktopPane1.add(estatisticacliente);
            estatisticacliente.setPosicao();
            estatisticacliente.toFront();
        }
        else if(!estatisticacliente.isVisible()){
            estatisticacliente.setVisible(true);
            jDesktopPane1.add(estatisticacliente);
            estatisticacliente.setPosicao();
            estatisticacliente.toFront();
        }
    }//GEN-LAST:event_btnestatisticaMouseClicked

    private void btnhistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoricoMouseClicked
        // TODO add your handling code here:
        
         //Algoritimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(historicocompras == null){
            historicocompras = new HistoricoCompras();
            historicocompras.setVisible(true);
            jDesktopPane1.add(historicocompras);
            historicocompras.setPosicao();
            historicocompras.toFront();
        }
        else if(!historicocompras.isVisible()){
            historicocompras.setVisible(true);
            jDesktopPane1.add(historicocompras);
            historicocompras.setPosicao();
            historicocompras.toFront();
        }
    }//GEN-LAST:event_btnhistoricoMouseClicked

    private void btnrelatoriodeestoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrelatoriodeestoqueMouseClicked
        // TODO add your handling code here:
        //Algoritimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(relatorioestoque == null){
            relatorioestoque = new RelatorioEstoque();
            relatorioestoque.setVisible(true);
            jDesktopPane1.add(relatorioestoque);
            relatorioestoque.setPosicao();
            relatorioestoque.toFront();
        }
        else if(!relatorioestoque.isVisible()){
            relatorioestoque.setVisible(true);
            jDesktopPane1.add(relatorioestoque);
            relatorioestoque.setPosicao();
            relatorioestoque.toFront();
        }
    }//GEN-LAST:event_btnrelatoriodeestoqueMouseClicked

    private void btnadditemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadditemMouseClicked
        // TODO add your handling code here:
        //Ação para chamar tela para add um novo item no estoque ou adicionar quantidade no estoque
       additem = new AddItem();
       additem.setVisible(true);
       jDesktopPane1.add(additem);
       additem.setPosicao();
       additem.toFront();
    }//GEN-LAST:event_btnadditemMouseClicked

    private void btnestatisticaequipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnestatisticaequipeMouseClicked
        // TODO add your handling code here:
         //Algoritimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(estatisticaconsultor == null){
            estatisticaconsultor = new EstatisticaConsultor();
            estatisticaconsultor.setVisible(true);
            jDesktopPane1.add(estatisticaconsultor);
            estatisticaconsultor.setPosicao();
            estatisticaconsultor.toFront();
        }
        else if(!estatisticaconsultor.isVisible()){
            estatisticaconsultor.setVisible(true);
            jDesktopPane1.add(estatisticaconsultor);
            estatisticaconsultor.setPosicao();
            estatisticaconsultor.toFront();
        }
    }//GEN-LAST:event_btnestatisticaequipeMouseClicked

    private void btnespalharmensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnespalharmensagemMouseClicked
        // TODO add your handling code here:
         //Algoritimo para abrir o JinternalFrame dentro do JDesktop e verificar se a janela já está aberta.
        if(espalharmensagem == null){
            espalharmensagem = new EspalharMensagem();
            espalharmensagem.setVisible(true);
            jDesktopPane1.add(espalharmensagem);
            espalharmensagem.setPosicao();
            espalharmensagem.toFront();
        }
        else if(!espalharmensagem.isVisible()){
            espalharmensagem.setVisible(true);
            jDesktopPane1.add(espalharmensagem);
            espalharmensagem.setPosicao();
            espalharmensagem.toFront();
        }
    }//GEN-LAST:event_btnespalharmensagemMouseClicked
/*
    
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
                
                
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcliente;
    private javax.swing.JButton btnadditem;
    private javax.swing.JButton btncarteirapedido;
    private javax.swing.JButton btnconsultacadastro;
    private javax.swing.JButton btnespalharmensagem;
    private javax.swing.JButton btnestatistica;
    private javax.swing.JButton btnestatisticaequipe;
    private javax.swing.JButton btnhistorico;
    private javax.swing.JButton btnimplantar;
    private javax.swing.JButton btnrelatoriodeestoque;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables


    

}


